import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "swe": {
          "C.C": "C.C",
          "SV_Kraft": "SV_Kraft",
          "Subscription": "Prenumeration",
          "Fuel type": "Bränsle typ",
          "User since 2018": "Användare sedan 2018",
          "Telephone  number": "Telefon nummer",
          "Chat": "Chatt",
          "Markets": "Marknadsföra",
          "filter product": "Filtrera produkter",
          "today": "Dagens val",
          "home-marketplace": "Marknad",
          "home-grocery": "Livsmedelsbutik",
          "home-Special-day": "Speciell dag",
          "home-restaurant": "Restaurang",
          "home-packages": "Paket",
          "home-orders": "Order",
          "home-users": "Användare",
          "sidebar-dashboard": "instrumentbräda",
          "cart-grocery-products": "Livsmedels Produkter",
          "cart-special-day-products": "Special Day-produkter",
          "hello": "Hallå",
          "welcome": "Välkommen",
          "failed": "Dessa uppgifter stämmer inte överens med våra uppgifter.",
          "password": "Det angivna lösenordet är felaktigt",
          "throttle":
              "För många inloggningsförsök. Försök igen om :seconds sekunder",
          "dashboard": "Instrumentbräda",
          "requests": "Förfrågningar",
          "all-products": "Alla produkter",
          "categories": "Kategorier",
          "Language": "Språk",
          "pending": "I väntan på",
          'Cancel': "Avbryt",
          "accept": "Acceptera",
          "reject": "Avvisa",
          "approved": "Godkänd",
          "details": "Detaljer",
          "image": "Bild",
          "price": "Pris",
          "product": "Produkt",
          "action": "Handling",
          "search": "Sök",
          "date": "Datum",
          "name": "namn",
          "next": "Nästa",
          "previous": "Tidigare",
          "all-right-reserved": "All Right Reserved",
          "customer": "Kund",
          "processing": "Bearbetning",
          "terms-condition": "Villkor",
          "sub category": "under kategori",
          "child category": "barn kategori",
          "Sorting": "Sortering",
          "Type of Ads": "Typ av annonser",
          "Advertisement": "Annons",
          "Seller details": "Säljar information",
          "Gear type": "Typ av växel",
          "Model": "Modell",
          "Brand": "varumärke",
          "Speed": "Fart",
          "Location": "Plats:",
          "Grocery  products": "Livsmedels produkter",
          "View All": "Visa alla",
          "Chicken": "Kyckling",
          "Special Day": "Speciell dag",
          "Header": "Rubrik",
          "PRODUCTS": "PRODUKTER",
          "FLOWERS": "BLOMMOR",
          "GIFTS": "GÅVOR",
          "OCCATIONS": "TILLFÄLLEN",
          "SPECIAL OCCATIONS": "SPECIELLA ANLÄGEN",
          "Contact": "Kontakt",
          "Rate App": "Betygsätt app",
          "Call Us": "Ring oss",
          "Share App": "Dela appen",
          "My Ads": "Mina annonser",
          "My Membership": "Mitt medlemskap",
          "Favourite": "Favorit",
          "Messages": "Meddelanden",
          "Privacy and Policy": "Sekretess och policy",
          "Help and Support": "Hjälp och support",
          "My Profile": "Min profil",
          "Settings": "inställningar",
          "Logout": "Logga ut",
          "Bookmarked Product": "Bokmärkt produkt",
          "Profile Settings": "Profilinställningar",
          "Bookmarks": "Bokmärken",
          "Save": "Spara",
          "Image from Camera": "Bild från kamera",
          "Image from Gallery": "Bild från Galleri",
          "Change your photo": "Ändra ditt foto",
          "Only JPG, JPEG, PNG format file supported.":
              "Endast fil i JPG-, JPEG-, PNG-format stöds.",
          "Enter your name": "Ange ditt namn",
          "Name *": "Namn *",
          "Enter your mail": "Ange din e-post",
          "Mail": "Post",
          "Address": "Adress",
          "Select Gender": "Välj kön",
          'Male': 'Manlig',
          'Female': 'Kvinna',
          'Other': 'Övrig',
          "Profile": "Profil",
          "coming soon": "kommer snart",
          "post left": "inlägg kvar",
          "No Product Found": "Ingen produkt hittades",
          'Title': 'Titel',
          "Show": "Visa ",
          "advertisements": " annonsar",
          "products category": "Produktkategori",
          "Let’s Sign You In": "Låt oss logga in dig",
          "Welcome back, you’ve been missed!":
              "Välkommen tillbaka, du har varit saknad!",
          "Phone Number": "Telefonnummer",
          'This field is required': "Detta fält är obligatoriskt",
          "SIGN IN": "LOGGA IN",
          "Don't have an account?": "Har du inget konto?",
          "Sign up": "Registrera dig",
          "Forget Password?": "Glöm lösenord?",
          "Getting Started": "Komma igång",
          "Create an account to continue!":
              "Skapa ett konto för att fortsätta!",
          "Username": "Användarnamn",
          "Email": "E-post",
          "By creating account, you are agree to our":
              "Genom att skapa ett konto godkänner du vår",
          "Term and Conditions": "Villkor och villkor",
          "Already have an account?": "Har du redan ett konto?",
          "Change Language": "Ändra språk",
          "Offers": "Erbjudanden",
          "Order History": "Beställningshistorik",
          "Call US": "Ring oss",
          "Payment History": "Betalningshistorik",
          "Wallet": "Plånbok",
          "Flowers In Vases": "Blommor I Vaser",
          "Flower & Chocolate": "Blomma & Choklad",
          "Gift Box": "Presentlåda",
          "Set Your Special Day": "Ställ in din speciella dag",
          'Add Product': "Lägg till produkt",
          "Categoris": "Kategorier",
          "Ad Type": "Annonstyp",
          "Heading": "Rubrik",
          'Please enter some text': "Vänligen skriv in lite text",
          "Text": "Text",
          "Sold": "Såld",
          "Zip Code": "Postnummer",
          "Reg No": "Reg nr",
          "Milage": "Milage",
          "Place": "Plats",
          "GearBox": "Växellåda",
          "Color": "Färg",
          "Car Type": "Bil typ",
          "Bike Type": "Cykeltyp",
          "Post": "Posta",
          "Text field error": "Textfältsfel",
          'enter your valid form': "skriv in ditt giltiga formulär",
          "Cart Screen": "Korgskärm",
          "Grocery Products": "Matvaror",
          "Special Day Products": "Special dags produkter",
          'Save to List': 'Spara till lista',
          'Total amount': 'Total belopp',
          'Something went wrong': 'Något gick fel',
          'Go to Checkout': 'Ga till Kassan',
          'Search': 'Sök',
          "Redeeam Coin": "Lös in mynt",
          "  Coin": "  Mynt",
          "Order id:": "Beställnings-id:",
          "Earned coins: ": "Intjänade mynt:",
          "Delivery Information": "Leveransinformation",
          "Fill all the field to continue!":
              "Fyll hela fältet för att fortsätta!",
          "Full Name": "Fullständiga namn",
          "Enter first name and last name": "Ange förnamn och efternamn",
          'At least 4 characters': "Minst 4 tecken",
          'Number must be at least 11 characters in length':
              "Numret måste vara minst 11 tecken långt",
          "Building no/ House no": "Building no/ House no",
          "Please enter": "Stig på",
          "Colony/ Locality": "Koloni/ort",
          "City": "Stad",
          "Area": "Område",
          "Example: House#123, Street#123, Block#123":
              "Exempel: Hus#123, Gata#123, Block#123",
          "Address saved": "Adressen har sparats",
          "Succsessfully saved": "Räddad framgångsrikt",
          "Address not saved": "Adressen har inte sparats",
          'CHECKOUT': 'KOLLA UPP',
          "Delivery Address": "Leveransadress",
          "Type Delivery Address": "Skriv leveransadress",
          "Pic date and time": "Bild datum och tid",
          'Order Summary': 'Ordersammanfattning',
          'Delivery Fee': 'Leveranskostnad',
          "Greetings": "Hälsningar",
          'Enter your greetings': "Skriv in dina hälsningar",
          "Congratulations.": "Grattis.",
          "Done": "Gjort",
          "PLACE ORDER": "BESTÄLLA",
          'Add Bookmarks Category': "Lägg till bokmärkeskategori",
          'Category Name': 'Kategori namn',
          'Grocery Bookmarks': "Bokmärken för livsmedelsbutiker",
          'No Category Found': "Ingen kategori hittades",
          "Coins : ": "Mynt:",
          'Cart': 'Vagn',
          'Delete Bookmarks Category': "Ta bort bokmärkeskategori",
          'Confirm': 'Bekräfta',
          'Error': 'Fel',
          'Category Not Deleted': "Kategori inte raderad",
          "Pick date and time": "Välj datum och tid",
          "date : ": "Datum : ",
          "kr": "kr",
          "Items": "Artiklar",
          "All Category": "Alla kategorier",
          'Add To Bookmarks.': "Lägg till i bokmärken.",
          'Success': 'Framgång',
          'Product Added To Bookmark': 'Produkt har lagts till i bokmärke',
          'Category Added': "Kategori tillagd",
          'Category Not Added': "Kategori ej tillagd",
          'Add': 'Lägg till',
          "Off price:": "Avpris:",
          "Discount: ": "Rabatt:",
          "Old Price:": "Gammalt pris:",
          "Special Discount": "Speciell rabatt",
          'Quantity': 'Kvantitet',
          'Add to cart': 'Lägg till i kundvagn',
          'Home': 'Hem',
          "Purchases": "Inköp",
          "Click here to create new reminder":
              "Klicka här för att skapa en ny påminnelse",
          'Title *': 'Titel *',
          "count": "räkna",
          "Time": "Tid",
          "Pick Time": "Plocka tid",
          "Pick Date": "Välj datum",
          "You are selected image": "Du är vald bild",
          "Upload cover image": "Ladda upp omslagsbild",
          "Submit": "Skicka in",
          "Title required": "Titel krävs",
          'Reminder': 'Påminnelse',
          "Days Left": "Dagar kvar",
          "Cart added succesfully": "Korgen har lagts till",
          "Successfully Purchased": "Lyckat inköpt",
          "Purchase": "Köp",
          "Sold throughout Iraq": "Säljs i hela Irak",
          "Post added successfully": "Inlägget har lagts till",
          "Offer price : ": "Erbjudande pris:",
          "Market price :": "Marknadspris :",
          "choose a language": "välj ett språk",
          'Search your product': "Sök efter din produkt",
          "Status": "Status",
          "Successfully copied": "Kopierat framgångsrikt",
          "Image picked faild.": "Bildvalt misslyckades.",
          "Record created successfully": "Record skapad framgångsrikt",
          "Buy with coin": "Buy with coin",
          "Cash on delivery": "Cash on delivery",
          "Enter address": "Enter address"
        },
        "eng": {
          "Enter address": "Enter address",
          "Buy with coin": "Buy with coin",
          "Cash on delivery": "Cash on delivery",
          "faild upload": "faild upload",
          "purchase some coin": "purchase some coin",
          "Image picked faild.": "Image picked faild.",
          "Successfully copied": "Successfully copied",
          "Status": "Status",
          "choose a language": "choose a language",
          "Market price :": "Market price :",
          "Post added successfully": "Post added successfully",
          "Sold throughout Iraq": "Sold throughout Iraq",
          "Successfully Purchased": "Successfully Purchased",
          "Cart added succesfully": "Cart added succesfully",
          "Days Left": "Days Left",
          "Title required": "Title required",
          "You are selected image": "You are selected image",
          "Time": "Time",
          'Title *': 'Title *',
          "Purchases": "Purchases",
          'Quantity': 'Quantity',
          "Old Price:": "Old Price:",
          "Off price:": "Off price:",
          'Category Added': 'Category Added',
          'Success': 'Success',
          "Items": "Items",
          "kr": "Kr",
          "Pick date and time": "Pick date and time",
          'Category Not Deleted': 'Category Not Deleted',
          'Confirm': 'Confirm',
          'Cancel': 'Cancel',
          'Delete Bookmarks Category': 'Delete Bookmarks Category',
          "Coins : ": "Coins : ",
          'Grocery Bookmarks': 'Grocery Bookmarks',
          'Category Name': 'Category Name',
          "PLACE ORDER": "PLACE ORDER",
          "Congratulations.": "Congratulations.",
          'Order Summary': 'Order Summary',
          "Type Delivery Address": "Type Delivery Address",
          'CHECKOUT': 'CHECKOUT',
          "Address not saved": "Address not saved",
          "Example: House#123, Street#123, Block#123":
              "Example: House#123, Street#123, Block#123",
          "Area": "Area",
          "Colony/ Locality": "Colony/ Locality",
          "Building no/ House no": "Building no/ House no",
          'Number must be at least 11 characters in length':
              'Number must be at least 11 characters in length',
          'At least 4 characters': 'At least 4 characters',
          "Enter first name and last name": "Enter first name and last name",
          "Fill all the field to continue!": "Fill all the field to continue!",
          "Earned coins: ": "Earned coins: ",
          "  Coin": "  Coin",
          'Search': 'Search',
          'Go to Checkout': 'Go to Checkout',
          'enter your valid form': 'enter your valid form',
          "Post": "Post",
          "Car Type": "Car Type",
          "C.C": "C.C",
          "GearBox": "GearBox",
          "Milage": "Milage",
          "Place": "Place",
          "Zip Code": "Zip Code",
          "Text": "Text",
          "Heading": "Heading",
          "Categoris": "Categoris",
          "Set Your Special Day": "Set Your Special Day",
          "Flower & Chocolate": "Flower & Chocolate",
          "Wallet": "Wallet",
          "Payment History": "Payment History",
          "Order History": "Order History",
          "Change Language": "Change Language",
          "Already have an account?": "Already have an account?",
          "Term and Conditions": "Term and Conditions",
          "By creating account, you are agree to our":
              "By creating account, you are agree to our",
          "Create an account to continue!": "Create an account to continue!",
          "Forget Password?": "Forget Password?",
          "Don't have an account?": "Don't have an account?",
          'This field is required': 'This field is required',
          "Let’s Sign You In": "Let’s Sign You In",
          "SV_Kraft": "SV_Kraft",
          'Title': 'Title',
          "post left": "post left",
          "Subscription": "Subscription",
          "coming soon": "coming soon",
          "Profile": "Profile",
          'Other': 'Other',
          'Female': 'Female',
          'Male': 'Male',
          "Select Gender": "Select Gender",
          "Address": "Address",
          "Mail": "Mail",
          "Enter your mail": "Enter your mail",
          "Name *": "Name *",
          "Enter your name": "Enter your name",
          "Change your photo": "Change your photo",
          "Image from Gallery": "Image from Gallery",
          "Image from Camera": "Image from Camera",
          "Save": "Save",
          "Bookmarks": "Bookmarks",
          "Profile Settings": "Profile Settings",
          "Bookmarked Product": "Bookmarked Product",
          "Logout": "Logout",
          "Settings": "Settings",
          "My Profile": "My Profile",
          "Privacy and Policy": "Privacy and Policy",
          "Help and Support": "Help and Support",
          "Messages": "Messages",
          "Favourite": "Favourite",
          "My Membership": "My Membership",
          "My Ads": "My Ads",
          "Share App": "Share App",
          "Rate App": "Rate App",
          "Contact": "Contact",
          "Call Us": "Call Us",
          "SPECIAL OCCATIONS": "SPECIAL OCCATIONS",
          "OCCATIONS": "OCCATIONS",
          "GIFTS": "GIFTS",
          "FLOWERS": "FLOWERS",
          "PRODUCTS": "PRODUCTS",
          "Header": "Header",
          "Special Day": "Special Day",
          "Chicken": "Chicken",
          "View All": "View All",
          "Grocery  products": "Grocery  products",
          "Location": "Location:",
          "Speed": "Speed",
          "Brand": "Brand",
          "Model": "Model",
          "Gear type": "Gear type",
          "Fuel type": "Fuel type",
          "User since 2018": "User since 2018",
          "Seller details": "Seller details",
          "Telephone  number": "Telephone no.",
          "Chat": "Chat",
          "Advertisement": "Advertisement",
          "Type of Ads": "Type of Ads",
          "Sorting": "Sorting",
          "child category": "child category",
          "sub category": "sub category",
          "Markets": "Market",
          "filter product": "Filter products",
          "today": "Today's picks",
          "home-marketplace": "Market place",
          "home-grocery": "Grocery",
          "home-Special-day": "Special Day",
          "home-restaurant": "Restaurant",
          "home-packages": "Packages",
          "home-orders": "Orders",
          "home-users": "Users",
          "sidebar-dashboard": "Dashboard",
          "cart-grocery-products": "Grocery Products",
          "cart-special-day-products": "Special Day Products",
          "hello": "Hello",
          "welcome": "Welcome",
          "failed": "These credentials do not match our records.",
          "password": "password",
          "throttle":
              "Too many login attempts. Please try again in :seconds seconds",
          "dashboard": "Dashboard",
          "requests": "Requests",
          "all-products": "All Products",
          "categories": "Categories",
          "Language": "Language",
          "pending": "Pending",
          "accept": "Accept",
          "reject": "Reject",
          "approved": "Approved",
          "details": "Details",
          "image": "Image",
          "price": "Price",
          "product": "Product",
          "action": "Action",
          "search": "Search",
          "date": "Date",
          "name": "Name",
          "next": "Next",
          "previous": "Previous",
          "all-right-reserved": "All Right Reserved",
          "customer": "Customer",
          "processing": "Processing",
          "terms-condition": "Terms and Conditions",
          "No Product Found": "No Product Found",
          "Show": "Show ",
          "advertisements": " advertisements",
          "products category": "Products category",
          "Welcome back, you’ve been missed!":
              "Welcome back, you’ve been missed!",
          "Phone Number": "Phone Number",
          "SIGN IN": "SIGN IN",
          "Sign up": "Sign up",
          "Getting Started": "Getting Started",
          "Username": "Username",
          "Email": "Email",
          "Offers": "Offers",
          "Call US": "Call US",
          "Flowers In Vases": "Flowers In Vases",
          "Gift Box": "Gift Box",
          'Add Product': 'Add Product',
          "Ad Type": "Ad Type",
          'Please enter some text': 'Please enter some text',
          "Sold": "Sold",
          "Reg No": "Reg No",
          "Color": "Color",
          "Bike Type": "Bike Type",
          "Text field error": "Text field error",
          "Cart Screen": "Cart Screen",
          "Grocery Products": "Grocery Products",
          "Special Day Products": "Special Day Products",
          'Save to List': 'Save to List',
          'Total amount': 'Total amount',
          'Something went wrong': 'Something went wrong',
          "Total": "Total",
          "Redeeam Coin": "Redeeam Coin",
          "Order id:": "Order id:",
          "Delivery Information": "Delivery Information",
          "Full Name": "Full Name",
          "Please enter": "Please enter",
          "City": "City",
          "Address saved": "Address saved",
          "Succsessfully saved": "Succsessfully saved",
          "Delivery Address": "Delivery Address",
          "Pic date and time": "Pic date and time",
          'Delivery Fee': 'Delivery Fee',
          "Greetings": "Greetings",
          'Enter your greetings': 'Enter your greetings',
          "Done": "Done",
          'Add Bookmarks Category': 'Add Bookmarks Category',
          'No Category Found': 'No Category Found',
          'Cart': 'Cart',
          'Error': 'Error',
          "Date : ": "Date : ",
          "All Category": "All Category",
          'Add To Bookmarks.': 'Add To Bookmarks.',
          'Product Added To Bookmark': 'Product Added To Bookmark',
          'Category Not Added': 'Category Not Added',
          'Add': 'Add',
          "Discount: ": "Discount: ",
          "Special Discount": "Special Discount",
          'Add to cart': 'Add to cart',
          'Home': 'Home',
          "Click here to create new reminder":
              "Click here to create new reminder",
          "count": "count",
          "Pick Time": "Pick Time",
          "Pick Date": "Pick Date",
          "Upload cover image": "Upload cover image",
          "Submit": "Submit",
          'Reminder': 'Reminder',
          "Purchase": "Purchase",
          "Offer price : ": "Offer price : ",
          "Only JPG, JPEG, PNG format file supported.":
              "Only JPG, JPEG, PNG format file supported.",
          'Search your product': 'Search your product',
          "Record created successfully": "Record created successfully",
          "OK": "OK",
          "Fill all fields": "Fill all fields",
          "Chat list": "Chat list",
          "Message here": "Message here",
          "Send": "Send",
          'Message': 'Message',
        },
        "arabic": {
          'Message': 'رسالة',
          "Send": "يرسل",
          "Message here": "رسالة هنا",
          "Enter address": "أدخل العنوان",
          "Chat list": "قائمة الدردشة",
          "Fill all fields": "املأ جميع الحقول",
          "Buy with coin": "الشراء بعملة",
          "Cash on delivery": "الدفع عند الاستلام",
          "OK": "نعم",
          "faild upload": "فشل تحميل",
          "purchase some coin": "شراء بعض العملات المعدنية",
          "Record created successfully": "تم إنشاء السجل بنجاح",
          "Image picked faild.": "فشل اختيار الصورة.",
          "Successfully copied": "تم النسخ بنجاح",
          "Status": "حالة",
          'Search your product': "ابحث في منتجك",
          "choose a language": "اختر لغة",
          "Only JPG, JPEG, PNG format file supported.":
              "يتم دعم ملفات بتنسيق JPG و JPEG و PNG فقط.",
          "Market price :": "سعر السوق :",
          "Offer price : ": "سعر العرض : ",
          "Post added successfully": "تمت إضافة المنشور بنجاح",
          "Sold throughout Iraq": "بيعت في جميع أنحاء العراق",
          "Purchase": "شراء",
          "Successfully Purchased": "تم شراؤها بنجاح",
          "Cart added succesfully": "تمت إضافة عربة التسوق بنجاح",
          "Days Left": "ايام متبقية",
          'Reminder': 'تذكير',
          "Title required": "العنوان مطلوب",
          "Submit": "إرسال",
          "Upload cover image": "تحميل صورة الغلاف",
          "You are selected image": "لقد تم تحديد الصورة",
          "Pick Date": "اختيار التاريخ",
          "Pick Time": "اختر وقت",
          "Time": "وقت",
          "count": "عدد",
          'Title *': 'لقب *',
          "Click here to create new reminder": "انقر هنا لإنشاء تذكير جديد",
          "Purchases": "المشتريات",
          'Home': 'مسكن',
          'Add to cart': 'أضف إلى السلة',
          'Quantity': 'كمية',
          "Special Discount": "خصم خاص",
          "Old Price:": "سعر قديم:",
          "Discount: ": "تخفيض: ",
          "Off price:": "السعر المخفَّض:",
          'Add': 'يضيف',
          'Category Not Added': "الفئة غير مضافة",
          'Category Added': "فئة المضافة",
          'Product Added To Bookmark': "تمت إضافة المنتج إلى إشارة مرجعية",
          'Success': 'النجاح',
          'Add To Bookmarks.': 'إضافة إلى المواقع المفضلة.',
          "filter product": "مرشح المنتج",
          "All Category": "كافة الفئات",
          "Items": "العناصر",
          "kr": "ع.د",
          "Date : ": "تاريخ : ",
          "Pick date and time": "اختر التاريخ والوقت",
          'Category Not Deleted': "الفئة غير محذوفة",
          'Error': 'خطأ',
          'Confirm': 'يتأكد',
          'Delete Bookmarks Category': "حذف فئة الإشارات المرجعية",
          'Cart': 'عربة التسوق',
          "Coins : ": "عملات معدنية : ",
          'Bookmarks': 'إشارات مرجعية',
          'No Category Found': "لم يتم العثور على فئة",
          'Grocery Bookmarks': "إشارات البقالة",
          'Cancel': 'يلغي',
          'Category Name': 'اسم التصنيف',
          'Add Bookmarks Category': "إضافة فئة الإشارات المرجعية",
          "PLACE ORDER": "مكان الامر",
          "Done": "فعله",
          "Congratulations.": "تهانينا.",
          'Enter your greetings': "أدخل تحياتك",
          "Greetings": "تحيات",
          'Delivery Fee': 'رسوم التوصيل',
          'Order Summary': "ملخص الطلب",
          "Pic date and time": "تاريخ ووقت الصورة",
          "Type Delivery Address": "اكتب عنوان التسليم",
          "Delivery Address": "عنوان التسليم",
          'CHECKOUT': 'الدفع',
          "Address not saved": "لم يتم حفظ العنوان",
          "Succsessfully saved": "تم الحفظ بنجاح",
          "Address saved": "العنوان محفوظ",
          "Example: House#123, Street#123, Block#123":
              "مثال: منزل رقم 123 ، شارع رقم 123 ، مجمع رقم 123",
          "Area": "مساحة",
          "City": "مدينة",
          "Colony/ Locality": "مستعمرة / محلية",
          "Please enter": "تفضل",
          "Building no/ House no": "رقم المبنى / رقم المنزل",
          'Number must be at least 11 characters in length':
              "يجب ألا يقل طول الرقم عن 11 حرفًا",
          'At least 4 characters': "4 أحرف على الأقل",
          "Enter first name and last name": "أدخل الاسم الأول واسم العائلة",
          "Full Name": "الاسم بالكامل",
          "Fill all the field to continue!": "املأ الحقل بالكامل للمتابعة!",
          "Delivery Information": "معلومات التوصيل",
          "Earned coins: ": "العملات المعدنية المكتسبة:",
          "Order id:": "رقم التعريف الخاص بالطلب:",
          "  Coin": "  عملة",
          "Redeeam Coin": "استبدال العملة",
          'Search': 'يبحث',
          "Total": "مجموع",
          'Go to Checkout': "الذهاب إلى الخروج",
          'Something went wrong': 'هناك خطأ ما',
          'Total amount': 'المبلغ الإجمالي',
          'Save to List': "حفظ في القائمة",
          "Special Day Products": "منتجات اليوم الخاص",
          "Grocery Products": "منتجات البقالة",
          "Cart Screen": "شاشة عربة التسوق",
          'enter your valid form': "أدخل نموذجك الصحيح",
          "Text field error": "خطأ في حقل النص",
          "Post": "بريد",
          "Bike Type": "نوع الدراجة",
          "Car Type": "نوع السيارة",
          "Color": "اللون",
          "C.C": "قوة المحرك",
          "GearBox": "ناقل الحركة",
          "Milage": "ميلاج",
          "Place": "مكان",
          "Reg No": "ريج لا",
          "Zip Code": "رمز بريدي",
          "Sold": "مُباع",
          "Text": "نص",
          'Please enter some text': "الرجاء إدخال نص",
          "Heading": "عنوان",
          "Ad Type": "نوع الإعلان",
          "Categoris": "فئات",
          'Add Product': 'أضف منتج',
          "Set Your Special Day": "حدد يومك الخاص",
          "Gift Box": "صندوق الهدايا",
          "Flower & Chocolate": "زهرة وشوكولا",
          "Flowers In Vases": "الزهور في المزهريات",
          "Wallet": "محفظة نقود",
          "Payment History": "سجل الدفع",
          "Call US": "اتصل بنا",
          "Order History": "تاريخ الطلب",
          "Offers": "عروض",
          "Change Language": "تغيير اللغة",
          "Already have an account?": "هل لديك حساب؟",
          "Term and Conditions": "شروط وأحكام",
          "By creating account, you are agree to our":
              "من خلال إنشاء الحساب ، فإنك توافق على",
          "Username": "اسم المستخدم",
          "Email": "بريد إلكتروني",
          "Create an account to continue!": "إنشاء حساب للمتابعة!",
          "Getting Started": "ابدء",
          "Forget Password?": "نسيت كلمة المرور؟",
          "Sign up": "تسجيل",
          "Don't have an account?": "ليس لديك حساب؟",
          "SIGN IN": "تسجيل الدخول",
          'This field is required': 'هذه الخانة مطلوبه',
          "Phone Number": "رقم الهاتف",
          "Welcome back, you’ve been missed!": "مرحبًا بعودتك ، لقد فاتتك!",
          "Let’s Sign You In": "هيا نسجل دخولك",
          "Show": "تبين ",
          "advertisements": " الإعلانات",
          "SV_Kraft": "تاج الاسواق",
          'Title': 'لقب',
          "No Product Found": "لم يتم العثور على منتج",
          "post left": "غادر آخر",
          "Subscription": "الاشتراك",
          "coming soon": "قريبا",
          "Profile": "حساب تعريفي",
          'Other': 'Other',
          'Female': 'Female',
          'Male': 'Male',
          "Select Gender": "حدد نوع الجنس",
          "Address": "تبوك",
          "Mail": "بريد",
          "Enter your mail": "أدخل بريدك",
          "Name *": "اسم *",
          "Enter your name": "أدخل أسمك",
          "Only JPG, JPEG, PNG format file supported.":
              "يتم دعم ملفات بتنسيق JPG و JPEG و PNG فقط.",
          "Change your photo": "غير صورتك",
          "Image from Gallery": "صورة من المعرض",
          "Image from Camera": "صورة من الكاميرا",
          "Save": "يحفظ",
          "Bookmarks": "إشارات مرجعية",
          "Profile Settings": "إعدادات الملف الشخصي",
          "Bookmarked Product": "منتج مرجعي",
          "Logout": "تسجيل خروج",
          "Settings": "إعدادات",
          "My Profile": "ملفي",
          "Privacy and Policy": "الخصوصية والسياسة",
          "Help and Support": "مساعدة و دعم",
          "Messages": "رسائل",
          "Favourite": "المفضل",
          "My Membership": "عضويتي",
          "My Ads": "إعلاناتي",
          "Share App": "شارك التطبيق",
          "Rate App": "قيم التطبيق",
          "Contact": "اتصال",
          "Call Us": "اتصل بنا",
          "SPECIAL OCCATIONS": "مناسبات خاصة",
          "OCCATIONS": "المناسبات",
          "GIFTS": "الهدايا",
          "FLOWERS": "زهور",
          "PRODUCTS": "منتجات",
          "Header": "رأس",
          "Special Day": "يوم خاص",
          "Chicken": "فرخة",
          "View All": "مشاهدة الكل",
          "Grocery  products": "منتجات البقالة",
          "Location": "موقع",
          "Speed": "سرعة",
          "Brand": "ماركة",
          "Model": "نموذج",
          "Gear type": "نوع العتاد",
          "Fuel type": "نوع الوقود",
          "User since 2018": "User since 2018",
          "Seller details": "تفاصيل البائع",
          "Telephone  number": "رقم هاتف",
          "Chat": "دردشة",
          "Advertisement": "الإعلانات",
          "Type of Ads": "نوع الإعلانات",
          "Sorting": "فرز",
          "child category": "فئة الطفل",
          "sub category": "تصنيف فرعي",
          "Markets": "الأسواق",
          "filter product": "منتج مرشح",
          "today": "اختيارات اليوم",
          "home-marketplace": "المتجر",
          "home-grocery": "خضروات",
          "home-Special-day": "يوم خاص",
          "home-restaurant": "مطعم",
          "home-packages": "الحزم",
          "home-orders": "الطلب",
          "home-users": "المستخدمون",
          "sidebar-dashboard": "Dashboard",
          "cart-grocery-products": "منتجات البقالة",
          "cart-special-day-products": "منتجات اليوم الخاص",
          "hello": "Hello",
          "welcome": "Welcome",
          "failed": "These credentials do not match our records.",
          "password": "كلمه السر",
          "throttle":
              "Too many login attempts. Please try again in :seconds seconds",
          "dashboard": "Dashboard",
          "requests": "Requests",
          "all-products": "All Products",
          "categories": "الفئات",
          "products category": "فئة المنتجات",
          "Language": "لغة",
          "pending": "Pending",
          "accept": "Accept",
          "reject": "Reject",
          "approved": "Approved",
          "details": "تفاصيل",
          "image": "صورة",
          "price": "السعر",
          "product": "منتج",
          "action": "فعل",
          "search": "يبحث",
          "date": "تاريخ",
          "name": "اسم",
          "next": "التالي",
          "previous": "سابق",
          "all-right-reserved": "جميع الحقوق محفوظة",
          "customer": "عميل",
          "processing": "Processing",
          "terms-condition": "الأحكام والشروط"
        }
      };
}
